var count = 0;
var alpha = 0;
var clicky = 0;
var doctors = 0
var pop = 1000;
var dying = 1;
var dying2 = 1;
var death = pop-death;
var hunger = 100;
var health = 100;

var alphakey = 0;


var snd = new Audio("alert.mp3");


//REAL WORLD TIMER********************

//***************INTRO
var person = prompt("Please enter your name:", "")
document.getElementById("title").innerHTML = person + "'s Bunker";

// **************** CHECKING FOR GAME OVER *****
setInterval(function(){
	if (pop < 0) {alert("Game Over. All of the people in the bunker has died."); location.reload()};
}, 100);

setInterval(function(){
	if (hunger >50) {dying = 1};
}, 100);

setInterval(function(){
	if (health >50) {dying2 = 1};
}, 100);



//*************** WORLD CLOCK **************
var myVar = setInterval(myTimer, 1000);

function myTimer() {
  var d = new Date()
document.getElementById("demo2").innerHTML = d.toLocaleTimeString();
}


//for login thingy
function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}

// for the create account thingy
function openform2() {
  document.getElementById("myform2").style.display = "block";
}
function closeform2() {
  document.getElementById("myform2").style.display = "none";
}

//for SETTINGS thingy
function openSettings() {
  document.getElementById("mySettings").style.display = "block";
}

function closeSettings() {
  document.getElementById("mySettings").style.display = "none";
}

function openHelp() {
	alert("BUNKER v1.0 \n\nBunker is a simple clicking game where you try to survive in an underground bunker. The goal of the game is to create a society in this underground bunker and not let the population count reach 0. You are able to purchase features and items, in return of money, which is generated by each click.\n\nStages for Bunker: \nStage 1: Access to generate coins, sponsor a child, cash printers, first-aid kit, food, workers, doctors, and alpha key. Alpha key unlocks stage two. ");
};
function on() {
  document.getElementById("overlay").style.display = "block";
alert("Paused")}

function off() {
  document.getElementById("overlay").style.display = "none";
}
//********************Progress Bar ***********************************************************

var elem = document.getElementById("myBar"); 
var width = 1;
setInterval(function(){width = pop/10; elem.style.width = width + '%';document.getElementById("mybar").width = width}, 100);










//****************** POPULATION AND DEATH************************************************

setInterval(function(){pop -= dying + dying2
			document.getElementById("population").innerHTML = "Population: " + pop;}, 1000);
	setInterval(function(){death = 1000 - pop
			document.getElementById("death").innerHTML = "Deaths: " + death;}, 1000)




//****************** HUNGER AND HEALTH************************************************

setInterval(function(){hunger -= 3
			document.getElementById("hunger").innerHTML = "Hunger: " + hunger + " %";
		if (50<hunger) {dying = 1
			};
		if (50>hunger) {dying = 2
			};
		if (25>hunger) {dying = 4;
};
		if (25 == hunger) {alert (person + "! Your people are dying from hunger.")
};
		if (5>hunger) {dying = 50}
}, 2000);


setInterval(function(){health -= 1
			document.getElementById("health").innerHTML = "Health: " + health + " %";
		if (50<hunger) {dying2 = 1
			};
		if (50>health) {dying2 = 2
			};
		if (25>health) {dying2 = 4;
};
		if (25 == health) {alert (person +"! Your people are dying from lack of health care.")
};
		if (5>health) {dying2 = 50}
}, 1000);
	

//******************Money Click ************************************************

var button = document.getElementById("click me")
button.onclick = function() {
	count += 1 + alpha;
	document.getElementById("sys").innerHTML = "Money: $ " + count;
};


//****************** TAX!!! ************************************************

var slider = document.getElementById("myRange");
var output = document.getElementById("tax");
output.innerHTML = slider.value; // Display the default slider value

// Update the current slider value (each time you drag the slider handle)
slider.oninput = function() {
  output.innerHTML = this.value;
}


//******************** ITEMS ITEMS ************************************************

function ms() {
	if (30 > count) {
  		alert("Not enough money. Generate more money.");

}	else { 
		pop += 1;
		count -= 30;
		document.getElementById("sys").innerHTML = "Money: $ " + count;
		document.getElementById("population").innerHTML = "Population: " + pop;
	}
}

var button2 = document.getElementById("click me");
function msg() {
	if (60 > count) {
  		alert("Not enough money. Generate more money.");

}	else { 
		alpha += 1;
		count -= 60;
		document.getElementById("sys").innerHTML = "Money: $ " + count;
		document.getElementById("particlecount").innerHTML = "Cash Printers: " + alpha;	
	}
}

function msg2() {
	if (2000 > count) {
  		alert("YOU DON'T HAVE ENOUGH CLICKS! Keep on clicking!");

}	else { 
		clicky += 1;
		count -= 2000;
		document.getElementById("sys").innerHTML = "Money: $ " + count;
		document.getElementById("clickycount").innerHTML = "Workers: " + clicky;
		setInterval(function(){count += 1
			document.getElementById("sys").innerHTML = "Money: $ " + count;}, 500);
	}
}

function msg3() {
	if (200 > count) {
  		alert("YOU DON'T HAVE ENOUGH CLICKS! Keep on clicking!");
}	else {
		count -= 200;
		hunger += 50;
		if (100 < hunger) {hunger = 100}
		document.getElementById("hunger").innerHTML = "Hunger: " + hunger + " %";
		document.getElementById("sys").innerHTML = "Money: $ " + count;
}
}

// FIRST AID KIT

function msg4() {
	if (100 > count) {
  		alert("YOU DON'T HAVE ENOUGH CLICKS! Keep on clicking!");
}	else {
		count -= 100;
		health += 30;
		if (100 < health) {health = 100}
		document.getElementById("health").innerHTML = "Health: " + health + " %";
		document.getElementById("sys").innerHTML = "Money: $ " + count;
}
}

//DOCTOR

function msg5() {
	if (10000 > count) {
  		alert("YOU DON'T HAVE ENOUGH CLICKS! Keep on clicking!");

}	else { 
		doctors += 1;
		count -= 10000;
		document.getElementById("sys").innerHTML = "Money: $ " + count;
		document.getElementById("Doctor").innerHTML = "Doctors: " + doctors;
		setInterval(function(){pop += 1
			document.getElementById("pop").innerHTML = "Population: " + pop;}, 1000);
	}
}

// ALPHA KEY STAGE 2 UNLOCK

function msg6() {
	if (20000 > count) {
  		alert("You don't have enough to unlock stage 2.");
}	else { 
		count -= 20000;

		//updating money and alpha key
		document.getElementById("alphakeydisable").disabled = true;
		document.getElementById("alphakeydisable").value = "Purchased";
		document.getElementById("sys").innerHTML = "Money: $ " + count;
		document.getElementById("key").innerHTML = "Alpha Key: 1";
		
		//showing stage two items
		document.getElementById("stagekitchen").style.display = "block";
		document.getElementById("stagerealestate").style.display = "block";
		document.getElementById("stagecashmachine").style.display = "block";
		document.getElementById("stageairpurifier").style.display = "block";
		document.getElementById("stageradio").style.display = "block";
		document.getElementById("stagebetaoperator").style.display = "block";

		//showing stage 2 stats
		document.getElementById("stat4").style.display = "block";

		//showing stage 2 alert
		var y = document.getElementById("snackbar");
  		y.className = "show";
  		setTimeout(function(){ y.className = y.className.replace("show", ""); }, 3000);
  		snd.play();

		
}}

function msg7(){
	document.getElementById("snackbar").stlye.display = "none"
}










function login() {
	var email = document.getElementById("email-field").value;
	var password = document.getElementById("password-field").value;

	firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
	  var errorCode = error.code;
	  
	  var errorMessage = error.message;
	  //w.alert("Error: " + errorCode + errorMessage );
	});

}



function signup() {

	var email = document.getElementById("email-field-signup").value;
	var password = document.getElementById("password-field-signup").value;

	firebase.auth().createUserWithEmailAndPassword(email, password).catch(function(error) {
	  // Handle Errors here.
	  var errorCode = error.code;
	  var errorMessage = error.message;
	  // ...
	});
}

function loginGoogle() {
	var provider = new firebase.auth.GoogleAuthProvider();
		firebase.auth().signInWithPopup(provider).then(function(result) {
		  // This gives you a Google Access Token. You can use it to access the Google API.
		  var token = result.credential.accessToken;
		  // The signed-in user info.
		  var user = result.user;
		  // ...
		}).catch(function(error) {
		  // Handle Errors here.
		  var errorCode = error.code;
		  var errorMessage = error.message;
		  // The email of the user's account used.
		  var email = error.email;
		  // The firebase.auth.AuthCredential type that was used.
		  var credential = error.credential;
		  // ...
		});
}

firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    // User is signed in.
    alert('hi')
    document.getElementById("welcomeMessage").style.display = "initial";
  } else {
    // No user is signed in.
    document.getElementById("welcomeMessage").style.display = "none";
  }
});

//******** LEVEL 2 ITEMS


/*
var alphavar = document.getElementById("alphabutton"),
	alphacount = 0;
alphavar.onclick = Function2() {
	alphacount = +=1;
document.getElementById("sys2").innerHTML = "Alpha: " + alphacount;
}
*/
